//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinema_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class bilet
    {
        public int bilet_id { get; set; }
        public int film_adi { get; set; }
        public int koltuk_id { get; set; }
        public int salon_id { get; set; }
        public int seans_id { get; set; }
    }
}
