//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinema_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class filmler
    {
        public int film_id { get; set; }
        public string film_adi { get; set; }
        public string film_turu { get; set; }
        public string yonetmen_adi { get; set; }
        public string yapimci_adi { get; set; }
        public string film_oyuncu { get; set; }
        public string film_tarih { get; set; }
        public string film_resim { get; set; }
    }
}
