//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinema_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class film_seans
    {
        public int film_id { get; set; }
        public string film_adi { get; set; }
        public string seans_tarih { get; set; }
        public string seans_saat { get; set; }
        public string salon_adi { get; set; }
        public string film_resim { get; set; }
    }
}
