//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinema_otomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class yapımcı
    {
        public int yapimci_id { get; set; }
        public string yapimci_adi { get; set; }
        public Nullable<int> film_id { get; set; }
    }
}
